server:
  port: 33555

spring:
  driverClassName:  "com.mysql.jdbc.Driver"
#  localdb: "jdbc:mysql://127.0.0.1:3306/test"
#  localdb: "jdbc:mysql://127.0.0.1:3306/world"
#  userName: "root"
#  password: "Chen_245193"
  localdb: "jdbc:mysql://39.107.139.11:3306/weatherPro?characterEncoding=utf8&useSSl=false"
  userName: "root"
  password: "Chen_12345"
  initialSize: 5
  maxIdle: 10
  maxActive: 50
  validationQuery: "select 1"
  destdriverClassName: "com.mysql.jdbc.Driver"
  destDb: "jdbc:mysql://127.0.0.1:3307/test2"
  destuserName: "root"
  destpassword: "chen12345"
  destinitialSize: 5
  destmaxIdle: 10
  destmaxActive: 50
  destvalidationQuery: "select 1"
page-helper-config:
    pageHelperPlugin: true



#logging:
#  path: C:\Users\chenkun\projectLog
#  file: test606.log
#  level:
#    root: debug
#    tk.mybatis: debug
#    com.ck: debug
#  file: test606.log
#  file: test606.log

