server:
  port: 33555

spring:
  driverClassName: "com.mysql.jdbc.Driver"
  localdb: "jdbc:mysql://127.0.0.1:3306/world"
  userName: "root"
  password: "chen_245193"
  initialSize: 5
  maxIdle: 10
  maxActive: 50
  validationQuery: "select 1"
  mvc:
    static-path-pattern: /static/**